### ISSUE TITLE
Question about duplicate predictions, matching and evaluation

### ISSUE THREAD

**Issue by dhuseljic** [asharakeh/pod_compare#10]
Hey, first of all, thank you for your excellent work.
I have a question regarding the matching of your evaluation which I might have overlooked in the paper or code.
A True Positive (TP) is defined as usual by a certain threshold and I am really curious about how you handle duplicate predictions: 
1. Do you match multiple predictions to a single ground truth (gt) object so you have multiple TPs per gt? Or is any duplicate considered as a False Positive (FP)? 
2. Similar to the first questions: Can a single prediction have multiple ground truths? 
3. Are you only using TPs to evaluate calibration errors and scoring rules? If so, do you then assess the accuracy (of matched boxes) to determine the marginal calibration error?

**Comment by asharakeh** [comment]
Sorry for the late response, I dont actively monitor this repo anymore. Duplicates are ignored, we choose the best detection and evaluate on that. For a better evaluation that resolves all your questions, please see my subsequent work at: https://github.com/asharakeh/probdet
