### ISSUE TITLE
Error in Conversion of BDD to COCO

### ISSUE THREAD

**Issue by richardtanai1** [asharakeh/pod_compare#3]
Running the convert script from the project directory
python /home/richard.tanai/codes/pod_compare/src/core/datasets/convert_bdd_to_coco.py --dataset-dir ~/datasets/bdd/

Gives the error
Traceback (most recent call last):

>   File "/home/richard.tanai/codes/pod_compare/src/core/datasets/convert_bdd_to_coco.py", line 159, in <module>
>     main(args)
>   File "/home/richard.tanai/codes/pod_compare/src/core/datasets/convert_bdd_to_coco.py", line 110, in main
>     training_image_list, training_annotation_list = create_coco_lists(
>   File "/home/richard.tanai/codes/pod_compare/src/core/datasets/convert_bdd_to_coco.py", line 53, in create_coco_lists
>     if annotation['category'] in category_keys:
> KeyError: 'category'

I have tried to check the dict by printing it before the error occurs around line 51
```
        annotations = grouped_per_frame[frame]
        for annotation in annotations:
            print(annotation)
            if annotation['category'] in category_keys:

```
The result of the print is as follows:
{'name': '0000f77c-6257be58.jpg', 'attributes': {'weather': 'clear', 'scene': 'city street', 'timeofday': 'daytime'}, 'timestamp': 10000, 'labels': [{'category': 'traffic light', 'attributes': {'occluded': False, 'truncated': False, 'trafficLightColor': 'green'}, 'manualShape': True, 'manualAttributes': True, 'box2d': {'x1': 1125.902264, 'y1': 133.184488, 'x2': 1156.978645, 'y2': 210.875445}, 'id': 0}, {'category': 'traffic light', 'attributes': {'occluded': False, 'truncated': False, 'trafficLightColor': 'green'}, 'manualShape': True, 'manualAttributes': True, 'box2d': {'x1': 1156.978645, 'y1': 136.637417, 'x2': 1191.50796, 'y2': 210.875443}, 'id': 1}, {'category': 'traffic sign', 'attributes': {'occluded': False, 'truncated': False, 'trafficLightColor': 'none'}, 'manualShape': True, 'manualAttributes': True, 'box2d': {'x1': 1101.731743, 'y1': 211.122087, 'x2': 1170.79037, 'y2': 233.566141}, 'id': 2}, {'category': 'traffic sign', 'attributes': {'occluded': False, 'truncated': True, 'trafficLightColor': 'none'}, 'manualShape': True, 'manualAttributes': True, 'box2d': {'x1': 0, 'y1': 0.246631, 'x2': 100.381647, 'y2': 122.825696}, 'id': 3}, {'category': 'car', 'attributes': {'occluded': False, 'truncated': False, 'trafficLightColor': 'none'}, 'manualShape': True, 'manualAttributes': True, 'box2d': {'x1': 45.240919, 'y1': 254.530367, 'x2': 357.805838, 'y2': 487.906215}, 'id': 4}, {'category': 'car', 'attributes': {'occluded': False, 'truncated': False, 'trafficLightColor': 'none'}, 'manualShape': True, 'manualAttributes': True, 'box2d': {'x1': 507.82755, 'y1': 221.727518, 'x2': 908.367588, 'y2': 442.715126}, 'id': 5}, {'category': 'traffic sign', 'attributes': {'occluded': False, 'truncated': True, 'trafficLightColor': 'none'}, 'manualShape': True, 'manualAttributes': True, 'box2d': {'x1': 0.156955, 'y1': 0.809282, 'x2': 102.417429, 'y2': 133.411856}, 'id': 6}, {'category': 'drivable area', 'attributes': {'areaType': 'direct'}, 'manualShape': True, 'manualAttributes': True, 'poly2d': [{'vertices': [[1280.195648, 626.372529], [1280.195648, 371.830705], [927.081254, 366.839689], [872.180076, 427.979637], [658.814135, 450.439209], [585.196646, 426.731883], [0, 517.817928], [0, 602.665203], [497.853863, 540.2775], [927.081254, 571.471352], [1280.195648, 626.372529]], 'types': 'LLLLLLLLCCC', 'closed': True}], 'id': 7}, {'category': 'lane', 'attributes': {'laneDirection': 'parallel', 'laneStyle': 'solid', 'laneType': 'road curb'}, 'manualShape': True, 'manualAttributes': True, 'poly2d': [{'vertices': [[503.674413, 373.137193], [357.797732, 374.672737]], 'types': 'LL', 'closed': False}], 'id': 8}, {'category': 'lane', 'attributes': {'laneDirection': 'parallel', 'laneStyle': 'solid', 'laneType': 'road curb'}, 'manualShape': True, 'manualAttributes': True, 'poly2d': [{'vertices': [[62.973282, 371.601649], [0, 368.53056]], 'types': 'LL', 'closed': False}], 'id': 9}, {'category': 'lane', 'attributes': {'laneDirection': 'parallel', 'laneStyle': 'solid', 'laneType': 'road curb'}, 'manualShape': True, 'manualAttributes': True, 'poly2d': [{'vertices': [[1274.517503, 376.208281], [905.986941, 371.601649]], 'types': 'LL', 'closed': False}], 'id': 10}]}

When downloading the BDD dataset
in bdd/labels/
I have renamed:
bdd100k_labels_images_train.json into train.json
bdd100k_labels_images_val.json into val.json

I would like to know how to fix this error

Thanks!

**Comment by asharakeh** [comment]
I havent seen this error before, but I also have an old version of BDD from 2018. I think it would be easier if I just share the converted labels. Please extract [these bdd coco-style labels](https://drive.google.com/file/d/1hOd3zX1Qt0_uV64uJBLidavjbtrv1tXI/view?usp=sharing) into the bdd/labels folder.

Let me know if these labels resolve your issue.

**Comment by richardtanai1** [comment]
Thanks! I was able to run the training script by using the bdd_labels that you have provided, but I have additional questions

Running the training with the bayes_od config
```
python src/train_net.py \
--num-gpus 1 \
--dataset-dir ~/datasets/bdd \
--config-file /home/richard.tanai/codes/pod_compare/src/configs/BDD-Detection/retinanet/retinanet_R_50_FPN_1x_reg_cls_var.yaml \
--random-seed 0 \
--resume

```
Evaluation results for bbox: 
|   AP   |  AP50  |  AP75  |  APs  |  APm   |  APl   |
|:------:|:------:|:------:|:-----:|:------:|:------:|
| 29.860 | 53.292 | 28.028 | 7.895 | 31.418 | 52.851 |
INFO: Per-category bbox AP: 
| category   | AP     | category   | AP     | category   | AP     |
|:-----------|:-------|:-----------|:-------|:-----------|:-------|
| car        | 45.679 | bus        | 41.049 | truck      | 39.554 |
| person     | 27.861 | rider      | 19.255 | bike       | 20.141 |
| motor      | 15.484 |            |        |            |        |


Performing the evalutation
```
python src/apply_net.py \
--dataset-dir ~/datasets/bdd \
--test-dataset bdd_val \
--config-file /home/richard.tanai/codes/pod_compare/src/configs/BDD-Detection/retinanet/retinanet_R_50_FPN_1x_reg_cls_var.yaml \
--inference-config /home/richard.tanai/codes/pod_compare/src/configs/Inference/bayes_od.yaml
```

I was able to get


|   Output Type    | Number of Instances | Cls Ignorance Score | Reg Ignorance Score |
| True Positives:  |     73631        |        0.8110       |       12.5145       |
| False Positives|     380069       |        0.1350       |       16.6284       |
| False Negatives|     1023        |          -          |          -          |


| Cls Marginal Calibration Error | Reg Expected Calibration Error | Reg Maximum Calibration Error | Cls Minimum Uncertainty Error | Reg Minimum Uncertainty Error |
|             0.0363             |             0.0531             |             0.1177            |             0.1358            |             0.2150            |




Is the metrics of the trained model consistent with one in your paper? the metrics seem to be a bit far off from those in Fig 8 Calibration Error and Fig 9 Minimum Uncertainty Error  in the paper

Also, near iteration 36000, the loss_box_reg became negative, is this behavior normal for the bayes_od configuration?

> iter: 36379 total_loss: 0.1463  loss_cls: 0.1388  loss_box_reg: -0.008727  time: 0.4328  data_time: 0.0101  lr: 0.0025  max_mem: 8091M
> iter: 89979  total_loss: -4.42  loss_cls: 0.1227  loss_box_reg: -4.539  time: 0.4325  data_time: 0.0100 lr: 2.5e-05  max_mem: 8091MM

**Comment by asharakeh** [comment]
1. Negative loss is normal. NLL loss can go negative, it is not restricted to positive range.
2. The numbers look ok, even better than the ones reported in the paper. The experiments in the paper were done on an **old version** of detectron2, pytorch 1.5, and CUDA 10.1.

3. BayesOD does not affect training. It is an inference script. You are training using **retinanet_R_50_FPN_1x_reg_cls_var.yaml**.

**Comment by richardtanai1** [comment]
Thank you for the explanation
