### ISSUE TITLE
Detectron2 Version

### ISSUE THREAD

**Issue by fabiankueppers** [asharakeh/pod_compare#7]
Hi guys, thanks for your code! In order to reproduce your results, I would like to ask you to update your requirements.txt file by the specific version of detectron2 that you have used. This is very important since there are major changes in Detectron2 core functionalities from version 0.1.3 up to 0.4. Thank you!

**Comment by asharakeh** [comment]
Hi @fabiankueppers, thank you for letting us know. Ill look into this as soon as possible.

**Comment by fabiankueppers** [comment]
Hi, are there any updates on this? Thank you!
