### ISSUE TITLE
Measuring PDQ

### ISSUE THREAD

**Issue by JacobOaks** [asharakeh/pod_compare#8]
Hi,

The corresponding paper to this code notes that PDQ "is evaluated at a single classification score threshold requiring practitioners to filter low scoring output detection results prior to evaluation", and the official COCO PDQ evaluation code has an argument "label_threshold" for this purpose. In the PDQ paper, they loosely use 0.5 as this threshold. I'm trying to calculate PDQ on models trained from this code and I can't find anything about what y'all set this threshold to, so I'm wondering if you used 0.5 as well or something else to produce your paper results.

Thanks!

**Comment by asharakeh** [comment]
Hi Jacob,

Our AP code provides the optimal score threshold that produces the best F-1 score for the given detector. We evaluate PDQ using this optimal score threshold for a fair evaluation of all methods.

https://github.com/asharakeh/pod_compare/blob/7f16c406bb258a0de96e2492797f6e960f21f8ec/src/offline_evaluation/compute_average_precision.py#L60

**Comment by JacobOaks** [comment]
Ah makes sense. Thanks so much.
